[build]
  command = "mkdir -p public/css public/js public/pages && cp index.html public/ && cp -r src/css/* public/css/ && cp -r src/js/* public/js/ && cp -r src/pages/* public/pages/"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NETLIFY_IDENTITY_ENABLED = "true"
