[build]
  publish = "public"
  command = "echo 'Static site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NETLIFY_IDENTITY_ENABLED = "true"
